apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-mlu-runtime
  namespace: orion
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orion-mlu-runtime
  template:
    metadata:
      labels:
        name: orion-mlu-runtime
    spec:
      #hostNetwork: true
      schedulerName: orion-scheduler
      containers:
        - name: orion-mlu-runtime
          #image: harbor.internal.cn:8443/orionx/orionx-mlu/orion-mlu-client:2.1.2-0826-tf2.15.5-mlu2.8.5-tk2.4.1-ubuntu18.04
          image: harbor.internal.cn:8443/orionx/orionx-mlu/orion-mlu-client:2.1.2-0826-tf1.15.5-mlu2.8.5-tk2.4.1-ubuntu18.04
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args: ["while true; do sleep 30; done;"]
          resources:
            requests:
              virtaitech.com/gpu: 1
            limits:
              virtaitech.com/gpu: 1
          env:
            - name : ORION_GMEM
              value : "15000"
            - name : ORION_RATIO
              value : "100"
            - name: ORION_VGPU
              value: "1"
            - name: ORION_RESERVED
              value: "0"
            - name: ORION_CROSS_NODE
              value: "1"
            - name: ORION_DEVICE_TYPE
              value: "MLU"
            - name : ORION_GROUP_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: ORION_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ORION_K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid