apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-runtime-a1
  namespace: orion
spec:
  replicas: 5
  selector:
    matchLabels:
      name: orion-runtime-a1
  template:
    metadata:
      labels:
        name: orion-runtime-a1
    spec:
      #hostNetwork: true
      #schedulerName: orion-scheduler
      nodeSelector:
        gpunode: "nvidia"
      containers:
        - name: orion-runtime-a1
          image: harbor.internal.cn:8443/orionx/native:tensorflow2.6.2-hvd0.24.2-cu11.2.0-cudnn8-py3.6-ubuntu20.04
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args: ["while true; do sleep 30; done;"]
          resources:
            requests:
              virtaitech.com/gpu: 1
              virtaitech.com/ratio: 40
              virtaitech.com/gmem: 10240
            limits:
              virtaitech.com/gpu: 1
              virtaitech.com/ratio: 40
              virtaitech.com/gmem: 10240
