apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-busybox
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: busybox
    app.kubernetes.io/name: busybox
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: busybox
      app.kubernetes.io/name: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: busybox
        app.kubernetes.io/name: busybox
    spec:
      containers:
        - name: busybox
          image: 'harbor.apulis.cn:8443/thirdparty/busybox:1.28'
          command:
            - tail
            - '-f'
            - /dev/null
          livenessProbe:
            exec:
              command:
                - cat
                - /dev/null
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - cat
                - /dev/null
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: RestartContainer
            - resourceName: nvidia.com/gpu
              restartPolicy: NotRequired
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
              ephemeral-storage: 1Gi
              nvidia.com/gpu: '1'
            limits:
              cpu: "1"
              memory: 2Gi
              ephemeral-storage: 1Gi
              nvidia.com/gpu: '1'
      restartPolicy: Always
      dnsPolicy: ClusterFirst
