apiVersion: batch/v1
kind: Job
metadata:
  name: busyjob
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: busyjob
    app.kubernetes.io/name: busyjob
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  manualSelector: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: busyjob
      app.kubernetes.io/name: busyjob
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: busyjob
        app.kubernetes.io/name: busyjob
    spec:
      containers:
        - name: busybox
          image: 'harbor.apulis.cn:8443/thirdparty/busybox:1.28'
          command:
            - tail
            - '-f'
            - /dev/null
          livenessProbe:
            exec:
              command:
                - cat
                - /dev/null
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - cat
                - /dev/null
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
              ephemeral-storage: 1Gi
            limits:
              cpu: "1"
              memory: 2Gi
              ephemeral-storage: 1Gi
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/role: master
  ttlSecondsAfterFinished: 3600
  completionMode: NonIndexed
  suspend: false